version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00" # (UTC)

    cooldown:
      default-days: 6 # match pnpm minimumReleaseAge
    
    labels:
      - "dependencies"
      - "npm"

    commit-message:
      prefix: "chore"
      include: "scope"

    groups:
      npm-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00" # (UTC)

    cooldown:
      default-days: 6
    
    labels:
      - "dependencies"
      - "github-actions"

    commit-message:
      prefix: "chore"
      include: "scope"

    groups:
      github-actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
